clear;

load('ms_mutation_transition_prob');

length_idx_old = 15; % ACx5
probs = ms_mutation_transition_prob(length_idx_old, :);

% set random number stream for reproducibility
rand_seed = RandStream('mlfg6331_64');

length_idx_new = datasample(...
    rand_seed, ...
    1:length(probs), ...
    50, ...
    'Replace', true, ...
    'Weights', probs ...
);
