genotyping:
  - n: 1
    targetNumReadsPerSample: 1000000
    noiseConstant: 0.01
    genotypingConfidenceThreshold: 0.01
  - n: 2
    targetNumReadsPerSample: 1000000
    noiseConstant: 0.01
    genotypingConfidenceThreshold: 0.02
  - n: 3
    targetNumReadsPerSample: 1000000
    noiseConstant: 0.01
    genotypingConfidenceThreshold: 0.05
