genotyping:
  - n: 1
    targetNumReadsPerSample: 1000000
    noiseConstant: 0.01
    genotypingConfidenceThreshold: 0.05
  - n: 2
    targetNumReadsPerSample: 2000000
    noiseConstant: 0.01
    genotypingConfidenceThreshold: 0.05
  - n: 3
    targetNumReadsPerSample: 3000000
    noiseConstant: 0.01
    genotypingConfidenceThreshold: 0.05
