ENV_MATLAB_KEY = 'matlab'
CONFIG_PATH_RELATIVE_OUTPUT = 'pathRelativeOutput'

FILE_SIMULATION_NEWICK = 'simulation.newick'
FILE_RECONSTRUCTED_NEWICK = 'reconstructed.newick'
FILE_RECONSTRUCTED_TMP_NEWICK = 'reconstructed.tmp.newick'
FILE_TRIPLETS_LIST_RAW = 'triplets-list.raw.txt'
FILE_TRIPLETS_LIST_CSV = 'triplets-list.csv'
FILE_TMC_LOG = 'tmc.log'
FILE_MUTATION_TABLE = 'mutation_table.txt'
FILE_RECONSTRUCTED_PNG = 'reconstructed.png'
FILE_COMPARISON_METRICS_RAW = 'scores.raw.out'
FILE_COMPARISON_METRICS_PRETTY = 'scores.pretty.out'
FILE_DIFF_METRICS = 'diff-score.json'
FILE_REPORT_HTML = 'report.html'
FILE_JSON_CONFIG_LIST = 'config.list'

PATH_ESTGT = './eSTGt/eSTGt'
PATH_SIMULATION_LIB = './src/simulation'
PATH_RECONSTRUCT_LIB = './src/reconstruction'
PATH_TREECMP_BIN = './TreeCmp/bin/treeCmp.jar'
